<?php
/*
CODE GENERATED BY: GRAFXSOFTWARE CODE GENERATOR
http://www.grafxsoftware.com
Error Page will be returned when in link ID not found.
*/

session_start();

include_once("./config.inc.php");

if (!isset($_SESSION['session_lang'])) {
	$session_lang = $LANG;
	$_SESSION['session_lang'] = $session_lang;
} else {
	$session_lang=$_SESSION['session_lang'];
}

include_once(INCLUDE_PATH . "cls_fast_template.php");
include_once(INCLUDE_LANGUAGE_PATH . $session_lang . ".inc.php");

$ft = new FastTemplate(TEMPLATE_PATH);
$ft -> define(array("main" => "template_index.html", "content" => "error.html"));

$ft->assign("ERROR_MESSAGE", LANG_NOID_ERROR_MESSAGE);

$ft->parse("BODY", array("content","main"));
$ft->showDebugInfo(ERROR_DEBUG);
$ft->FastPrint();

?>