<?php
/*
CODE GENERATED BY: GRAFXSOFTWARE CODE GENERATOR
http://www.grafxsoftware.com
Error Page will be returned when in link ID not found.
*/

session_start();

include_once("./config.inc.php");

if (!isset($_SESSION['session_lang'])) {
	$session_lang = $LANG;
	$_SESSION['session_lang'] = $session_lang;
} else {
	$session_lang=$_SESSION['session_lang'];
}

include_once(INCLUDE_PATH . "cls_fast_template.php");
include_once(INCLUDE_LANGUAGE_PATH . $session_lang . ".inc.php");
include_once(INCLUDE_PATH . "cls_universal_mailsender.php");

$ft = new FastTemplate(TEMPLATE_PATH);
$ft -> define(array("main" => "template_index.html", "content" => "error.html"));

$ft->assign("ERROR_MESSAGE", LANG_NOID_ERROR_MESSAGE);

if (header("HTTP/1.0 403 Forbidden"));
$error_code = '403 Forbidden';

if (header("HTTP/1.0 404 Not Found"));
$error_code = '404 Not Found';

			# Gather visitor information
			$ip = getenv ("REMOTE_ADDR");                // IP Address
			$server_name = getenv ("SERVER_NAME");       // Server Name
			$request_uri = getenv ("REQUEST_URI");       // Requested URI
			$http_ref = getenv ("HTTP_REFERER");         // HTTP Referer
			$http_agent = getenv ("HTTP_USER_AGENT");    // User Agent
			$error_date = date("D M j Y g:i:s a T");     // Error Date
	
			/*
			Send error to ADMIN.
			High traffic websites have the potential to generate A LOT of 
			emails so make sure you setup some sort of email filter for these 
			error notifications so they don't flood your inbox. 
			*/
			$ftea = new FastTemplate(EMAIL_PATH);
			$ftea->define(array("main"=>"template_index.html", "content"=>"error.html"));
			$ftea->assign("IP",$ip);
			$ftea->assign("SERVER_NAME",$server_name);
			$ftea->assign("REQUEST_URI",$request_uri);
			$ftea->assign("HTTP_REF",$http_ref);
			$ftea->assign("HTTP_AGENT",$http_agent);
			$ftea->assign("ERROR_DATE",$error_date);
			$ftea->assign("ERROR_CODE",$error_code);
			$ftea->multiple_assign_define("CONF_");
			$ftea->multiple_assign_define("LANG_");
			$ftea->parse("CONTENT", "content");
			$ftea->parse("BODY", "main");
			$subject=$error_code;
			$message = $ftea->fetch("BODY");
			
			$mail = new UniversalMailSender("2");
			$mail->setToAddress(EMAIL_INREG,EMAIL_NAME);
			$mail->setFromAddress(EMAIL_INREG,EMAIL_NAME);
			$mail->setSubject($subject);
			$mail->setType(2);
			$mail->setHtmlMessage($message);
			$mail->SendMail();

$ft->parse("BODY", array("content","main"));
$ft->showDebugInfo(ERROR_DEBUG);
$ft->FastPrint();

?>